version: 1.0.{build}

image: 
  - Visual Studio 2019
  - Ubuntu

before_build:
  - nuget restore

build_script:
  - dotnet build DistributedLock.sln -c Release
  
# only test categories that don't depend on external things
test:
  categories:
    - CI

for: 
  - 
    matrix: 
      only: 
        - 
          image: "Visual Studio 2019"
    test: 
      categories: 
        - CI
        - CIWindows